version: '3'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4-debian-10
    environment:
      MONGO_INITDB_ROOT_USERNAME: chozoi
      MONGO_INITDB_ROOT_PASSWORD: zoiohc
      MONGODB_DATABASE: cz-crawl-data

    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/configs/mongodb"
      
volumes:
  mongodb_data:
    driver: local
